# Generated by Django 3.2.5 on 2021-07-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_added',
            field=models.DateTimeField(verbose_name='date added'),
        ),
    ]
