# Generated by Django 3.2.5 on 2021-07-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210701_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, default='teaching', max_length=30),
        ),
    ]
