# Generated by Django 3.2.5 on 2021-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(default='teaching', max_length=39),
        ),
    ]
